name: test

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install dependencies
        env:
          NPM_TOKEN_GITHUB: ${{ secrets.NPM_TOKEN_GITHUB }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN_GITHUB}" >> $HOME/.npmrc
          npm ci --production
      - name: test release
        run: npm run release -- -e dev
